### PR TITLE
feat: add edit note feature

### LINKED ISSUE #1: Editing
Hello,

Just installed this Add-On and it's brilliant and I love it.
One question though...Is it not possible to edit a note once you add it?

Thanks!

### PR DESCRIPTION
**Pull request by tresorama**
This PR would close #1 

---

Added "Edit" note feature.

Refactored a bit of the "state" logic of `Notes.jsx` to handle the new feature.
Added Pencil icon.

https://github.com/getflywheel/local-addon-notes/assets/47954700/32be6ce0-2410-4dca-8811-d2f44b6b9fc1

### CODE REVIEW

**Comment by tresorama** [comment]
Let me know if something is not ok.

PS: forgive the "text" of the first note in the video, I'm tired and didn't know what I was writing either 😎

**Comment by tresorama** [comment]
Commenting to bring attention to this...

**Comment by carterlando** [comment]
+1
Please release this

**Review by adamperrry — APPROVED** [review]
This looks really great, you did an awesome job matching the icon style too 😄 I'm going to approve and merge it in, and I'll start the process for cutting a release, testing it internally, and publishing. 

Thanks for taking the time to make the add-on better!

**Comment by tresorama** [comment]
Great! I enjoyed adding this 😎

Let me know if you need to...

**Pull request merged**
